---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- if .Values.deployment.secrets.credentialFile.path }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: {{ .Values.deployment.secrets.credentialFile.path }}
            {{- end }}
            {{- if .Values.deployment.secrets.awsConfig.path }}
            - name: CONFIG_FILE
              value: {{ .Values.deployment.secrets.awsConfig.path }}
            {{- end }}
            {{- if .Values.deployment.test.enabled }}
            - name: TEST
              value: {{ .Values.deployment.test.enabled | quote }}
            {{- end }}
            {{- if ne .Values.deployment.network.name "mainnet"  }} # if variable is not set the app assumes it's mainnet and will use mainnet signing byte
            - name: NETWORK
              value: {{ .Values.deployment.network.name | quote }}
            {{- end }}
          volumeMounts:
            {{- with .Values.deployment.secrets.credentialFile }}
            - name:  {{ .releaseName }}-credential-file
              mountPath: {{ .dir | quote }}
            {{- end }}
            {{- with .Values.deployment.secrets.awsConfig }}
            - name:  {{ .releaseName }}-credential-file
              mountPath: {{ .dir | quote }}
            {{- end }}
      volumes:
        {{- with .Values.deployment.secrets.credentialFile }}
        - name: {{ .releaseName }}-aws-config
          secret:
            secretName: {{ .releaseName }}
            defaultMode: 0600
            items:
              - key: {{ .name }}
                path: {{ .name }}.json
        {{- end }}
        {{- with .Values.deployment.secrets.awsConfig }}
        - name: {{ .releaseName }}-aws-config
          secret:
            secretName: {{ .releaseName }}
            defaultMode: 0600
            items:
              - key: {{ .name }}
                path: {{ .name }}.json
        {{- end }}
